### ISSUE TITLE
SFML 2.6

### ISSUE THREAD

**Issue by PasVegan** [Guigui220D/zig-sfml-wrapper#48]
A new version of SFML and CSFML came out. I was wondering if someone will modify this wrapper to include new features ?

**Comment by Guigui220D** [comment]
I'm really surprised I didn't get a notification or an email from this... I havent been working on the wrapper for a while, I don't think I will be doing that soon, but it shouldn't be too complicated if someone else wants to do it.

**Comment by Guigui220D** [comment]
I updated the build.zig to the newer zig version, so I should be tackling the move to 2.6.1 soon hopefully

**Comment by Guigui220D** [comment]
Did the update and it might not be very exhaustive becasue the changelog wasn't very useful in showing me what changed, but it works for 2.6.1
I'll keep working on it anyways and if you see a missing feature you want just ask!
