### ISSUE TITLE
non ascii characters are not diplayed correctly

### ISSUE THREAD

**Issue by IbrahimOuhamou** [Guigui220D/zig-sfml-wrapper#54]
when I try to render `ب` or `é` I get squares instead of what I wanted

do you know if it is a csfml problem or a zig problem? can you please fix it if you know how?

thanks in advance, also thank you for making this wrapper

**Comment by Guigui220D** [comment]
Hello, thanks for making an issue,
Indeed I think I havent implemented unicode yet! So only ascii works as of now.... I will try to do it in the following days, i dont know what capabilites SFML has in that regard but it does have unicode functions so it should be possible.

**Comment by IbrahimOuhamou** [comment]
thanks a lot, may God guide you and protect you

**Comment by Guigui220D** [comment]
![image](https://github.com/Guigui220D/zig-sfml-wrapper/assets/24529384/48195943-a26b-4b8e-9164-088456ce56b8)

You're able to use `sf.toUnicodeAlloc` and `sf.toUnicodeComptime` to get unicode from UTF-8 (SFML doesn't work directly with UTF-8 sadly...), and `text.setStringUnicode` and `window.setTitleUnicode` to use this unicode.

Tell me if you need anything else :)

**Comment by IbrahimOuhamou** [comment]
where can I find the `sf.toUnicodeAlloc`? I updated the `build.zig.zon` but I don't know where to find it

what is in your `sf` struct?

**Comment by IbrahimOuhamou** [comment]
thanks a lot man
