### ISSUE TITLE
panics on touch pad scroll

### ISSUE THREAD

**Issue by IbrahimOuhamou** [Guigui220D/zig-sfml-wrapper#60]
```
/home/user/.cache/zig/p/1220fd00dbf098b935ed4771943579d1a04be454fe5b42b11e1ba5205e050ac5ac34/src/window/event.zig:39:21: 0x18454a89 in _fromCSFML (quran-warsh)
            else => @panic("Unknown event!"),
```

I don't think it has to panic when the event is not defined as technologies do change and add more events (`event.eye_entered` might become I thing and only God knows)

**Comment by Guigui220D** [comment]
True! If you want you can change this and i'll pull, thanks

**Comment by IbrahimOuhamou** [comment]
@Guigui220D I think making it return an error would be good? But errors in zig are a breaking change but alhamdo li Allah the solution would be minor

The current state is:
```
while(window.pullEvent()) |event| {
    // do stuff if you want
    switch(event) {}
    // do stuff if you want
}
```


But after adding the error it would be either:
1.
```
// don't do it in 'main()` since it will
// probably break on the supposed
// `eye_entred` event
// but you can do it if you have a seperate function
while(try window.pullEvent()) |event| {
    // do stuff if you want
    switch(event) {}
    // do stuff if you want
}
```

2.
```
// I think it would be better to use
// this in main since your app does
// not have to panic
while(window.pullEvent()) |event| {
    // do stuff if you want
    switch(event) {}
    // do stuff if you want
} else |err| {
    // if (err != .unknown)
    std.log.error("alhamdo li Allah err: '{any}'", .{err});
}
```

The other option is to do an `else => {}`

**Comment by Guigui220D** [comment]
Actually I think an error would complicate things (and crash in most cases as well...)
I think the best option is to print something and do nothing like `Encountered unhandled error code [] ?`
In any ways i should add the support for this specific event haha

**Comment by IbrahimOuhamou** [comment]
but in std they do error unions, like in `OutOfMemory`
@Guigui220D

**Comment by IbrahimOuhamou** [comment]
@Guigui220D I have implemented the error unions, but I have a better idea

we can just return an `.undefined` event
benefits:
- lets the user handle it (we might make it return the `c_event`)
- does not force crashing

good?

anyways, I am making a Quran app, want to read it?

**Comment by Guigui220D** [comment]
The reason I don't want to make it a error is that it changes the functions' signature, for what is just a mistake from my part (forgetting to implement a new event)
Thanks for your contribution but I will go ahead and make it a warning message ^^ (and i might return the .undefined or .unimplemented as you said)
I am not interested in the Quran but i'm glad you're putting my sfml wrapper to use, thanks for your contributions :)
